var annotated_dup =
[
    [ "zpp", null, [
      [ "bits", null, [
        [ "numbers", null, [
          [ "big_endian", "structzpp_1_1bits_1_1numbers_1_1big__endian.html", "structzpp_1_1bits_1_1numbers_1_1big__endian" ]
        ] ],
        [ "options", null, [
          [ "endian", null, [
            [ "big", "structzpp_1_1bits_1_1options_1_1endian_1_1big.html", null ],
            [ "little", "structzpp_1_1bits_1_1options_1_1endian_1_1little.html", null ]
          ] ],
          [ "append", "structzpp_1_1bits_1_1options_1_1append.html", null ],
          [ "reserve", "structzpp_1_1bits_1_1options_1_1reserve.html", null ],
          [ "resize", "structzpp_1_1bits_1_1options_1_1resize.html", null ],
          [ "alloc_limit", "structzpp_1_1bits_1_1options_1_1alloc__limit.html", null ],
          [ "enlarger", "structzpp_1_1bits_1_1options_1_1enlarger.html", null ],
          [ "no_fit_size", "structzpp_1_1bits_1_1options_1_1no__fit__size.html", null ],
          [ "no_enlarge_overflow", "structzpp_1_1bits_1_1options_1_1no__enlarge__overflow.html", null ],
          [ "enlarge_overflow", "structzpp_1_1bits_1_1options_1_1enlarge__overflow.html", null ],
          [ "no_size", "structzpp_1_1bits_1_1options_1_1no__size.html", null ],
          [ "size1b", "structzpp_1_1bits_1_1options_1_1size1b.html", null ],
          [ "size2b", "structzpp_1_1bits_1_1options_1_1size2b.html", null ],
          [ "size4b", "structzpp_1_1bits_1_1options_1_1size4b.html", null ],
          [ "size8b", "structzpp_1_1bits_1_1options_1_1size8b.html", null ],
          [ "size_native", "structzpp_1_1bits_1_1options_1_1size__native.html", null ],
          [ "size_varint", "structzpp_1_1bits_1_1options_1_1size__varint.html", null ]
        ] ],
        [ "endian", null, [
          [ "big", "structzpp_1_1bits_1_1options_1_1endian_1_1big.html", null ],
          [ "little", "structzpp_1_1bits_1_1options_1_1endian_1_1little.html", null ]
        ] ],
        [ "traits", null, [
          [ "is_unique_ptr", "structzpp_1_1bits_1_1traits_1_1is__unique__ptr.html", null ],
          [ "is_unique_ptr&lt; std::unique_ptr&lt; Type, std::default_delete&lt; Type &gt; &gt; &gt;", "structzpp_1_1bits_1_1traits_1_1is__unique__ptr_3_01std_1_1unique__ptr_3_01Type_00_01std_1_1defaue378557b789df2f7ba0d98a9bd13878a.html", null ],
          [ "is_shared_ptr", "structzpp_1_1bits_1_1traits_1_1is__shared__ptr.html", null ],
          [ "is_shared_ptr&lt; std::shared_ptr&lt; Type &gt; &gt;", "structzpp_1_1bits_1_1traits_1_1is__shared__ptr_3_01std_1_1shared__ptr_3_01Type_01_4_01_4.html", null ],
          [ "variant_impl", "structzpp_1_1bits_1_1traits_1_1variant__impl.html", null ],
          [ "variant_impl&lt; Variant&lt; Types... &gt; &gt;", "structzpp_1_1bits_1_1traits_1_1variant__impl_3_01Variant_3_01Types_8_8_8_01_4_01_4.html", null ],
          [ "variant_checker", "structzpp_1_1bits_1_1traits_1_1variant__checker.html", null ],
          [ "variant_checker&lt; Variant&lt; Types... &gt; &gt;", "structzpp_1_1bits_1_1traits_1_1variant__checker_3_01Variant_3_01Types_8_8_8_01_4_01_4.html", null ],
          [ "tuple", "structzpp_1_1bits_1_1traits_1_1tuple.html", null ],
          [ "tuple&lt; Tuple&lt; Types... &gt; &gt;", "structzpp_1_1bits_1_1traits_1_1tuple_3_01Tuple_3_01Types_8_8_8_01_4_01_4.html", null ],
          [ "visitor", "structzpp_1_1bits_1_1traits_1_1visitor.html", null ],
          [ "id_serializable", "structzpp_1_1bits_1_1traits_1_1id__serializable.html", null ]
        ] ],
        [ "basic_out", "classzpp_1_1bits_1_1basic__out.html", null ],
        [ "out", "classzpp_1_1bits_1_1out.html", null ],
        [ "in", "classzpp_1_1bits_1_1in.html", null ],
        [ "members", "structzpp_1_1bits_1_1members.html", null ],
        [ "protocol", "structzpp_1_1bits_1_1protocol.html", null ],
        [ "serialization_id", "structzpp_1_1bits_1_1serialization__id.html", null ],
        [ "errc", "structzpp_1_1bits_1_1errc.html", null ],
        [ "access", "structzpp_1_1bits_1_1access.html", "structzpp_1_1bits_1_1access" ],
        [ "destructor_guard", "structzpp_1_1bits_1_1destructor__guard.html", null ],
        [ "known_id_variant", "structzpp_1_1bits_1_1known__id__variant.html", null ],
        [ "known_dynamic_id_variant", "structzpp_1_1bits_1_1known__dynamic__id__variant.html", null ],
        [ "string_literal", "structzpp_1_1bits_1_1string__literal.html", null ],
        [ "bytes", "classzpp_1_1bits_1_1bytes.html", null ],
        [ "option", "structzpp_1_1bits_1_1option.html", null ],
        [ "optional_ptr", "structzpp_1_1bits_1_1optional__ptr.html", null ],
        [ "sized_item", "structzpp_1_1bits_1_1sized__item.html", null ],
        [ "sized_item_ref", "structzpp_1_1bits_1_1sized__item__ref.html", null ],
        [ "pb_reserved", "structzpp_1_1bits_1_1pb__reserved.html", null ],
        [ "pb_map", "structzpp_1_1bits_1_1pb__map.html", null ],
        [ "pb_field_fundamental", "structzpp_1_1bits_1_1pb__field__fundamental.html", null ],
        [ "pb_field_struct", "structzpp_1_1bits_1_1pb__field__struct.html", null ],
        [ "pb", "structzpp_1_1bits_1_1pb.html", "structzpp_1_1bits_1_1pb" ],
        [ "function_traits", "structzpp_1_1bits_1_1function__traits.html", null ],
        [ "function_traits&lt; Return(*)(Arguments...)&gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07_5_08_07Arguments_8_8_8_08_4.html", null ],
        [ "function_traits&lt; Return(*)(Arguments...) noexcept &gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07_5_08_07Arguments_8_8_8_08_01noexcept_01_4.html", null ],
        [ "function_traits&lt; Return(This::*)(Arguments...)&gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07This_1_1_5_08_07Arguments_8_8_8_08_4.html", null ],
        [ "function_traits&lt; Return(This::*)(Arguments...) noexcept &gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07This_1_1_5_08_07Arguments_8_8_8_08_01noexcept_01_4.html", null ],
        [ "function_traits&lt; Return(This::*)(Arguments...) const &gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07This_1_1_5_08_07Arguments_8_8_8_08_01const_01_4.html", null ],
        [ "function_traits&lt; Return(This::*)(Arguments...) const noexcept &gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07This_1_1_5_08_07Arguments_8_8_8_08_01const_01noexcept_01_4.html", null ],
        [ "function_traits&lt; Return(*)()&gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07_5_08_07_08_4.html", null ],
        [ "function_traits&lt; Return(*)() noexcept &gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07_5_08_07_08_01noexcept_01_4.html", null ],
        [ "function_traits&lt; Return(This::*)()&gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07This_1_1_5_08_07_08_4.html", null ],
        [ "function_traits&lt; Return(This::*)() noexcept &gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07This_1_1_5_08_07_08_01noexcept_01_4.html", null ],
        [ "function_traits&lt; Return(This::*)() const &gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07This_1_1_5_08_07_08_01const_01_4.html", null ],
        [ "function_traits&lt; Return(This::*)() const noexcept &gt;", "structzpp_1_1bits_1_1function__traits_3_01Return_07This_1_1_5_08_07_08_01const_01noexcept_01_4.html", null ],
        [ "value_or_errc", "structzpp_1_1bits_1_1value__or__errc.html", null ],
        [ "bind", "structzpp_1_1bits_1_1bind.html", null ],
        [ "bind_opaque", "structzpp_1_1bits_1_1bind__opaque.html", null ],
        [ "rpc_impl", "structzpp_1_1bits_1_1rpc__impl.html", "structzpp_1_1bits_1_1rpc__impl" ],
        [ "rpc_checker", "structzpp_1_1bits_1_1rpc__checker.html", null ],
        [ "varint", "structzpp_1_1bits_1_1varint.html", null ],
        [ "append", "structzpp_1_1bits_1_1options_1_1append.html", null ],
        [ "reserve", "structzpp_1_1bits_1_1options_1_1reserve.html", null ],
        [ "resize", "structzpp_1_1bits_1_1options_1_1resize.html", null ],
        [ "alloc_limit", "structzpp_1_1bits_1_1options_1_1alloc__limit.html", null ],
        [ "enlarger", "structzpp_1_1bits_1_1options_1_1enlarger.html", null ],
        [ "no_fit_size", "structzpp_1_1bits_1_1options_1_1no__fit__size.html", null ],
        [ "no_enlarge_overflow", "structzpp_1_1bits_1_1options_1_1no__enlarge__overflow.html", null ],
        [ "enlarge_overflow", "structzpp_1_1bits_1_1options_1_1enlarge__overflow.html", null ],
        [ "no_size", "structzpp_1_1bits_1_1options_1_1no__size.html", null ],
        [ "size1b", "structzpp_1_1bits_1_1options_1_1size1b.html", null ],
        [ "size2b", "structzpp_1_1bits_1_1options_1_1size2b.html", null ],
        [ "size4b", "structzpp_1_1bits_1_1options_1_1size4b.html", null ],
        [ "size8b", "structzpp_1_1bits_1_1options_1_1size8b.html", null ],
        [ "size_native", "structzpp_1_1bits_1_1options_1_1size__native.html", null ],
        [ "size_varint", "structzpp_1_1bits_1_1options_1_1size__varint.html", null ]
      ] ]
    ] ]
];