cmake_minimum_required(VERSION 4.4)
project(zppbits VERSION 4.7.3 DESCRIPTION "placeholder" LANGUAGES C CXX)
set(CMAKE_EXPERIMENTAL_FIND_CPS_PACKAGES ON)
set(CMAKE_CXX_MODULE_STD ON)
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_C_STANDARD 23)
set(CMAKE_C_EXTENSIONS ON)
include(GNUInstallDirs)
add_subdirectory(src)
include(options.cmake)
if(BUILD_TESTING)
    include(CTest)
    add_subdirectory(tests)
endif()
